/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author HP
 */
public class GD_Chinh extends javax.swing.JFrame {
     
   public  Border default_border = BorderFactory.createMatteBorder(0, 0   , 3, 0, new Color(153,153,153));
   public Border active_border = BorderFactory.createMatteBorder(0, 0   , 3, 0, new Color(153,204,255));
   public JButton [] buttons;
    /**
     * Creates new form GD_Chinh
     */
    

    public GD_Chinh() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        addBorder();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Main = new javax.swing.JPanel();
        pnl_Menu_main = new javax.swing.JPanel();
        pnl_Menu_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnl_Menu_button = new javax.swing.JPanel();
        pnl_button_TongQuan = new javax.swing.JPanel();
        lbl_logo_TongQuan = new javax.swing.JLabel();
        lbl_title_TongQuan = new javax.swing.JLabel();
        pnl_button_BanHang = new javax.swing.JPanel();
        lbl_logo_BanHang = new javax.swing.JLabel();
        lbl_title_BanHang = new javax.swing.JLabel();
        pnl_button_SanPham = new javax.swing.JPanel();
        lbl_logo_SanPham = new javax.swing.JLabel();
        lbl_title_SanPham = new javax.swing.JLabel();
        pnl_button_KhachHang = new javax.swing.JPanel();
        lbl_logo_KhachHang = new javax.swing.JLabel();
        lbl_title_KhachHang = new javax.swing.JLabel();
        pnl_button_NhanVien = new javax.swing.JPanel();
        lbl_logo_NhanVien = new javax.swing.JLabel();
        lbl_title_NhanVien = new javax.swing.JLabel();
        pnl_button_TimKiem = new javax.swing.JPanel();
        lbl_logo_TimKiem = new javax.swing.JLabel();
        lbl_title_TimKiem = new javax.swing.JLabel();
        pnl_button_HeThong = new javax.swing.JPanel();
        lbl_logo_HeThong = new javax.swing.JLabel();
        lbl_title_HeThong = new javax.swing.JLabel();
        pnl_button_ThongKe = new javax.swing.JPanel();
        lbl_logo_ThongKe = new javax.swing.JLabel();
        lbl_title_ThongKe = new javax.swing.JLabel();
        pnl_ThongTinTaiKhoan = new javax.swing.JPanel();
        lbl_icon_TaiKhoan = new javax.swing.JLabel();
        lbl_title_TaiKhoan = new javax.swing.JLabel();
        pnl_btn_exit = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        pnl_FormTongQuan = new javax.swing.JPanel();
        lbl_text_TongQuan = new javax.swing.JLabel();
        pnl_FormBanHang = new javax.swing.JPanel();
        lbl_text_BanHang = new javax.swing.JLabel();
        pnl_menuTab_BanHang = new javax.swing.JPanel();
        btn_tab_BanHang = new javax.swing.JButton();
        pnl_FormSanPham = new javax.swing.JPanel();
        lbl_text_SanPham = new javax.swing.JLabel();
        pnl_menuTab_SanPham = new javax.swing.JPanel();
        btn_tab_SanPham = new javax.swing.JButton();
        btn_tab_LoaiSanPham = new javax.swing.JButton();
        btn_tab_NhaCungCap = new javax.swing.JButton();
        pnl_FormKhachHang = new javax.swing.JPanel();
        lbl_text_KhachHang = new javax.swing.JLabel();
        pnl_FormNhanVien = new javax.swing.JPanel();
        lbl_text_NhanVien = new javax.swing.JLabel();
        pnl_FormTimKiem = new javax.swing.JPanel();
        lbl_text_TimKiem = new javax.swing.JLabel();
        pnl_FormHeThong = new javax.swing.JPanel();
        lbl_text_HeThong = new javax.swing.JLabel();
        pnl_FormThongKe = new javax.swing.JPanel();
        lbl_text_ThongKe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Main.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Menu_main.setBackground(new java.awt.Color(153, 204, 255));
        pnl_Menu_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Menu_logo.setBackground(new java.awt.Color(153, 204, 255));

        lbl_logo.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 85)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setText("DAD ");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fashion");

        javax.swing.GroupLayout pnl_Menu_logoLayout = new javax.swing.GroupLayout(pnl_Menu_logo);
        pnl_Menu_logo.setLayout(pnl_Menu_logoLayout);
        pnl_Menu_logoLayout.setHorizontalGroup(
            pnl_Menu_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_Menu_logoLayout.setVerticalGroup(
            pnl_Menu_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Menu_logoLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnl_Menu_main.add(pnl_Menu_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        pnl_Menu_button.setBackground(new java.awt.Color(153, 204, 255));
        pnl_Menu_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_button_TongQuan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_button_TongQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_TongQuanMouseClicked(evt);
            }
        });

        lbl_logo_TongQuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_TongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/house.png"))); // NOI18N

        lbl_title_TongQuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_TongQuan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_TongQuan.setText("Tổng Quản");

        javax.swing.GroupLayout pnl_button_TongQuanLayout = new javax.swing.GroupLayout(pnl_button_TongQuan);
        pnl_button_TongQuan.setLayout(pnl_button_TongQuanLayout);
        pnl_button_TongQuanLayout.setHorizontalGroup(
            pnl_button_TongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_TongQuanLayout.createSequentialGroup()
                .addComponent(lbl_logo_TongQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_TongQuanLayout.setVerticalGroup(
            pnl_button_TongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_TongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_TongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        pnl_button_BanHang.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_BanHangMouseClicked(evt);
            }
        });

        lbl_logo_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/trade.png"))); // NOI18N

        lbl_title_BanHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_BanHang.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_BanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnl_button_BanHangLayout = new javax.swing.GroupLayout(pnl_button_BanHang);
        pnl_button_BanHang.setLayout(pnl_button_BanHangLayout);
        pnl_button_BanHangLayout.setHorizontalGroup(
            pnl_button_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_BanHangLayout.createSequentialGroup()
                .addComponent(lbl_logo_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_BanHangLayout.setVerticalGroup(
            pnl_button_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 50));

        pnl_button_SanPham.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_SanPhamMouseClicked(evt);
            }
        });

        lbl_logo_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/checklist.png"))); // NOI18N

        lbl_title_SanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_SanPham.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_SanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout pnl_button_SanPhamLayout = new javax.swing.GroupLayout(pnl_button_SanPham);
        pnl_button_SanPham.setLayout(pnl_button_SanPhamLayout);
        pnl_button_SanPhamLayout.setHorizontalGroup(
            pnl_button_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_SanPhamLayout.createSequentialGroup()
                .addComponent(lbl_logo_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_SanPhamLayout.setVerticalGroup(
            pnl_button_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 50));

        pnl_button_KhachHang.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_KhachHangMouseClicked(evt);
            }
        });

        lbl_logo_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/target.png"))); // NOI18N

        lbl_title_KhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_KhachHang.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_KhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout pnl_button_KhachHangLayout = new javax.swing.GroupLayout(pnl_button_KhachHang);
        pnl_button_KhachHang.setLayout(pnl_button_KhachHangLayout);
        pnl_button_KhachHangLayout.setHorizontalGroup(
            pnl_button_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_KhachHangLayout.createSequentialGroup()
                .addComponent(lbl_logo_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_KhachHangLayout.setVerticalGroup(
            pnl_button_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 50));

        pnl_button_NhanVien.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_NhanVienMouseClicked(evt);
            }
        });

        lbl_logo_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/employee.png"))); // NOI18N

        lbl_title_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_NhanVien.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_NhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout pnl_button_NhanVienLayout = new javax.swing.GroupLayout(pnl_button_NhanVien);
        pnl_button_NhanVien.setLayout(pnl_button_NhanVienLayout);
        pnl_button_NhanVienLayout.setHorizontalGroup(
            pnl_button_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_NhanVienLayout.createSequentialGroup()
                .addComponent(lbl_logo_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_NhanVienLayout.setVerticalGroup(
            pnl_button_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 50));

        pnl_button_TimKiem.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_TimKiemMouseClicked(evt);
            }
        });

        lbl_logo_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/search.png"))); // NOI18N

        lbl_title_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_TimKiem.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_TimKiem.setText("Tìm Kiếm");

        javax.swing.GroupLayout pnl_button_TimKiemLayout = new javax.swing.GroupLayout(pnl_button_TimKiem);
        pnl_button_TimKiem.setLayout(pnl_button_TimKiemLayout);
        pnl_button_TimKiemLayout.setHorizontalGroup(
            pnl_button_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_TimKiemLayout.createSequentialGroup()
                .addComponent(lbl_logo_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_TimKiemLayout.setVerticalGroup(
            pnl_button_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 50));

        pnl_button_HeThong.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_HeThong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_HeThongMouseClicked(evt);
            }
        });

        lbl_logo_HeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_HeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/system.png"))); // NOI18N

        lbl_title_HeThong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_HeThong.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_HeThong.setText("Hệ Thống");

        javax.swing.GroupLayout pnl_button_HeThongLayout = new javax.swing.GroupLayout(pnl_button_HeThong);
        pnl_button_HeThong.setLayout(pnl_button_HeThongLayout);
        pnl_button_HeThongLayout.setHorizontalGroup(
            pnl_button_HeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_HeThongLayout.createSequentialGroup()
                .addComponent(lbl_logo_HeThong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_HeThongLayout.setVerticalGroup(
            pnl_button_HeThongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_HeThong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_HeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 50));

        pnl_button_ThongKe.setBackground(new java.awt.Color(153, 204, 255));
        pnl_button_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_button_ThongKeMouseClicked(evt);
            }
        });

        lbl_logo_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/analytics.png"))); // NOI18N

        lbl_title_ThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_ThongKe.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_ThongKe.setText("Thống Kê");

        javax.swing.GroupLayout pnl_button_ThongKeLayout = new javax.swing.GroupLayout(pnl_button_ThongKe);
        pnl_button_ThongKe.setLayout(pnl_button_ThongKeLayout);
        pnl_button_ThongKeLayout.setHorizontalGroup(
            pnl_button_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_button_ThongKeLayout.createSequentialGroup()
                .addComponent(lbl_logo_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        pnl_button_ThongKeLayout.setVerticalGroup(
            pnl_button_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lbl_title_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_Menu_button.add(pnl_button_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 50));

        pnl_ThongTinTaiKhoan.setBackground(new java.awt.Color(153, 204, 255));

        lbl_icon_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icon_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/user.png"))); // NOI18N

        lbl_title_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_title_TaiKhoan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_TaiKhoan.setText("Thông Tin Nhân Viên");

        javax.swing.GroupLayout pnl_ThongTinTaiKhoanLayout = new javax.swing.GroupLayout(pnl_ThongTinTaiKhoan);
        pnl_ThongTinTaiKhoan.setLayout(pnl_ThongTinTaiKhoanLayout);
        pnl_ThongTinTaiKhoanLayout.setHorizontalGroup(
            pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_icon_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_title_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        pnl_ThongTinTaiKhoanLayout.setVerticalGroup(
            pnl_ThongTinTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lbl_icon_TaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pnl_Menu_button.add(pnl_ThongTinTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 100));

        pnl_btn_exit.setBackground(new java.awt.Color(153, 204, 255));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVSicon/exit (2).png"))); // NOI18N

        javax.swing.GroupLayout pnl_btn_exitLayout = new javax.swing.GroupLayout(pnl_btn_exit);
        pnl_btn_exit.setLayout(pnl_btn_exitLayout);
        pnl_btn_exitLayout.setHorizontalGroup(
            pnl_btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_exitLayout.setVerticalGroup(
            pnl_btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_Menu_button.add(pnl_btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 210, 50));

        pnl_Menu_main.add(pnl_Menu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 670));

        pnl_Main.add(pnl_Menu_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 800));

        pnl_FormTongQuan.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormTongQuan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_TongQuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_TongQuan.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_TongQuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_TongQuan.setText("Tổng Quan");
        pnl_FormTongQuan.add(lbl_text_TongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormTongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormBanHang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormBanHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_BanHang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_BanHang.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_BanHang.setText("Bán Hàng");
        pnl_FormBanHang.add(lbl_text_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_menuTab_BanHang.setBackground(new java.awt.Color(255, 255, 255));

        btn_tab_BanHang.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_BanHang.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_tab_BanHang.setForeground(new java.awt.Color(153, 153, 153));
        btn_tab_BanHang.setText("Bán Hàng");
        btn_tab_BanHang.setBorder(null);
        btn_tab_BanHang.setContentAreaFilled(false);
        btn_tab_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tab_BanHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuTab_BanHangLayout = new javax.swing.GroupLayout(pnl_menuTab_BanHang);
        pnl_menuTab_BanHang.setLayout(pnl_menuTab_BanHangLayout);
        pnl_menuTab_BanHangLayout.setHorizontalGroup(
            pnl_menuTab_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuTab_BanHangLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_tab_BanHang)
                .addContainerGap(938, Short.MAX_VALUE))
        );
        pnl_menuTab_BanHangLayout.setVerticalGroup(
            pnl_menuTab_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuTab_BanHangLayout.createSequentialGroup()
                .addComponent(btn_tab_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_FormBanHang.add(pnl_menuTab_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1090, 60));

        pnl_Main.add(pnl_FormBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormSanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_SanPham.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_SanPham.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_SanPham.setText("Sản Phẩm");
        pnl_FormSanPham.add(lbl_text_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_menuTab_SanPham.setBackground(new java.awt.Color(255, 255, 255));

        btn_tab_SanPham.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_SanPham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_tab_SanPham.setForeground(new java.awt.Color(153, 153, 153));
        btn_tab_SanPham.setText("Sản Phẩm");
        btn_tab_SanPham.setBorder(null);
        btn_tab_SanPham.setContentAreaFilled(false);
        btn_tab_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tab_SanPhamActionPerformed(evt);
            }
        });

        btn_tab_LoaiSanPham.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_LoaiSanPham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_tab_LoaiSanPham.setForeground(new java.awt.Color(153, 153, 153));
        btn_tab_LoaiSanPham.setText("Loại Sản Phẩm");
        btn_tab_LoaiSanPham.setBorder(null);
        btn_tab_LoaiSanPham.setContentAreaFilled(false);

        btn_tab_NhaCungCap.setBackground(new java.awt.Color(255, 255, 255));
        btn_tab_NhaCungCap.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btn_tab_NhaCungCap.setForeground(new java.awt.Color(153, 153, 153));
        btn_tab_NhaCungCap.setText("Nhà Cung Cấp");
        btn_tab_NhaCungCap.setBorder(null);
        btn_tab_NhaCungCap.setContentAreaFilled(false);

        javax.swing.GroupLayout pnl_menuTab_SanPhamLayout = new javax.swing.GroupLayout(pnl_menuTab_SanPham);
        pnl_menuTab_SanPham.setLayout(pnl_menuTab_SanPhamLayout);
        pnl_menuTab_SanPhamLayout.setHorizontalGroup(
            pnl_menuTab_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuTab_SanPhamLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_tab_SanPham)
                .addGap(44, 44, 44)
                .addComponent(btn_tab_LoaiSanPham)
                .addGap(45, 45, 45)
                .addComponent(btn_tab_NhaCungCap)
                .addContainerGap(657, Short.MAX_VALUE))
        );
        pnl_menuTab_SanPhamLayout.setVerticalGroup(
            pnl_menuTab_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menuTab_SanPhamLayout.createSequentialGroup()
                .addGroup(pnl_menuTab_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_tab_SanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_tab_LoaiSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tab_NhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_FormSanPham.add(pnl_menuTab_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1090, 50));

        pnl_Main.add(pnl_FormSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_KhachHang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_KhachHang.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_KhachHang.setText("Khách Hàng");
        pnl_FormKhachHang.add(lbl_text_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_NhanVien.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_NhanVien.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_NhanVien.setText("Nhân Viên");
        pnl_FormNhanVien.add(lbl_text_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormTimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_TimKiem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_TimKiem.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_TimKiem.setText("Tìm Kiếm");
        pnl_FormTimKiem.add(lbl_text_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormHeThong.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormHeThong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_HeThong.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_HeThong.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_HeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_HeThong.setText("Hệ Thống");
        pnl_FormHeThong.add(lbl_text_HeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        pnl_FormThongKe.setBackground(new java.awt.Color(255, 255, 255));
        pnl_FormThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_text_ThongKe.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_text_ThongKe.setForeground(new java.awt.Color(0, 153, 204));
        lbl_text_ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text_ThongKe.setText("Thông Kê");
        pnl_FormThongKe.add(lbl_text_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 138, 50));

        pnl_Main.add(pnl_FormThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1090, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addBorder(){
        buttons = new JButton[3];
        buttons[0] = btn_tab_SanPham;
        buttons[1] = btn_tab_LoaiSanPham;
        buttons[2] = btn_tab_NhaCungCap;
        
        for (JButton button : buttons) {
            button.setBorder(default_border);
        }
        setButtonBorder(btn_tab_SanPham);
        addAction();
    }
    
    //set border active
    public void setButtonBorder(JButton button){
        for (JButton btn : buttons) {
            btn.setBorder(default_border);
            btn.setForeground(new Color(153,153,153));
        }
        button.setBorder(active_border);
        button.setForeground(Color.black);
    }
    //add even
    public void addAction(){
        for (JButton button : buttons) {
            button.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    setButtonBorder(button);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                   
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    
                }
            });
        }
    }
    
    private void pnl_button_TongQuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_TongQuanMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(true);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(Color.white);
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground(new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
        
        


    }//GEN-LAST:event_pnl_button_TongQuanMouseClicked

    private void pnl_button_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_BanHangMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(true);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(Color.white);
        pnl_button_SanPham.setBackground(new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_BanHangMouseClicked

    private void pnl_button_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_SanPhamMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(true);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( Color.white);
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_SanPhamMouseClicked

    private void pnl_button_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_KhachHangMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(true); 
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( new Color(153,204,255));
        pnl_button_KhachHang.setBackground(Color.white);
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_KhachHangMouseClicked

    private void pnl_button_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_NhanVienMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(true);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(Color.white);
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_NhanVienMouseClicked

    private void pnl_button_TimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_TimKiemMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(true);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(Color.white);
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_TimKiemMouseClicked

    private void pnl_button_HeThongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_HeThongMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(true);
        pnl_FormThongKe.setVisible(false);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(Color.white);
        pnl_button_ThongKe.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_pnl_button_HeThongMouseClicked

    private void pnl_button_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_button_ThongKeMouseClicked
        // TODO add your handling code here:
        pnl_FormTongQuan.setVisible(false);
        pnl_FormBanHang.setVisible(false);
        pnl_FormSanPham.setVisible(false);
        pnl_FormKhachHang.setVisible(false);
        pnl_FormNhanVien.setVisible(false);
        pnl_FormTimKiem.setVisible(false);
        pnl_FormHeThong.setVisible(false);
        pnl_FormThongKe.setVisible(true);
        
        pnl_button_TongQuan.setBackground(new Color(153,204,255));
        pnl_button_BanHang.setBackground(new Color(153,204,255));
        pnl_button_SanPham.setBackground( new Color(153,204,255));
        pnl_button_KhachHang.setBackground(new Color(153,204,255));
        pnl_button_NhanVien.setBackground(new Color(153,204,255));
        pnl_button_TimKiem.setBackground(new Color(153,204,255));
        pnl_button_HeThong.setBackground(new Color(153,204,255));
        pnl_button_ThongKe.setBackground(Color.white);
    }//GEN-LAST:event_pnl_button_ThongKeMouseClicked

    private void btn_tab_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tab_BanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tab_BanHangActionPerformed

    private void btn_tab_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tab_SanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tab_SanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_Chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tab_BanHang;
    private javax.swing.JButton btn_tab_LoaiSanPham;
    private javax.swing.JButton btn_tab_NhaCungCap;
    private javax.swing.JButton btn_tab_SanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icon_TaiKhoan;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_logo_BanHang;
    private javax.swing.JLabel lbl_logo_HeThong;
    private javax.swing.JLabel lbl_logo_KhachHang;
    private javax.swing.JLabel lbl_logo_NhanVien;
    private javax.swing.JLabel lbl_logo_SanPham;
    private javax.swing.JLabel lbl_logo_ThongKe;
    private javax.swing.JLabel lbl_logo_TimKiem;
    private javax.swing.JLabel lbl_logo_TongQuan;
    private javax.swing.JLabel lbl_text_BanHang;
    private javax.swing.JLabel lbl_text_HeThong;
    private javax.swing.JLabel lbl_text_KhachHang;
    private javax.swing.JLabel lbl_text_NhanVien;
    private javax.swing.JLabel lbl_text_SanPham;
    private javax.swing.JLabel lbl_text_ThongKe;
    private javax.swing.JLabel lbl_text_TimKiem;
    private javax.swing.JLabel lbl_text_TongQuan;
    private javax.swing.JLabel lbl_title_BanHang;
    private javax.swing.JLabel lbl_title_HeThong;
    private javax.swing.JLabel lbl_title_KhachHang;
    private javax.swing.JLabel lbl_title_NhanVien;
    private javax.swing.JLabel lbl_title_SanPham;
    private javax.swing.JLabel lbl_title_TaiKhoan;
    private javax.swing.JLabel lbl_title_ThongKe;
    private javax.swing.JLabel lbl_title_TimKiem;
    private javax.swing.JLabel lbl_title_TongQuan;
    private javax.swing.JPanel pnl_FormBanHang;
    private javax.swing.JPanel pnl_FormHeThong;
    private javax.swing.JPanel pnl_FormKhachHang;
    private javax.swing.JPanel pnl_FormNhanVien;
    private javax.swing.JPanel pnl_FormSanPham;
    private javax.swing.JPanel pnl_FormThongKe;
    private javax.swing.JPanel pnl_FormTimKiem;
    private javax.swing.JPanel pnl_FormTongQuan;
    private javax.swing.JPanel pnl_Main;
    private javax.swing.JPanel pnl_Menu_button;
    private javax.swing.JPanel pnl_Menu_logo;
    private javax.swing.JPanel pnl_Menu_main;
    private javax.swing.JPanel pnl_ThongTinTaiKhoan;
    private javax.swing.JPanel pnl_btn_exit;
    private javax.swing.JPanel pnl_button_BanHang;
    private javax.swing.JPanel pnl_button_HeThong;
    private javax.swing.JPanel pnl_button_KhachHang;
    private javax.swing.JPanel pnl_button_NhanVien;
    private javax.swing.JPanel pnl_button_SanPham;
    private javax.swing.JPanel pnl_button_ThongKe;
    private javax.swing.JPanel pnl_button_TimKiem;
    private javax.swing.JPanel pnl_button_TongQuan;
    private javax.swing.JPanel pnl_menuTab_BanHang;
    private javax.swing.JPanel pnl_menuTab_SanPham;
    // End of variables declaration//GEN-END:variables
}
